services:
  aws-scanner:
    image: 189060532132.dkr.ecr.ap-northeast-2.amazonaws.com/deployguard-aws-scanner
    container_name: deployguard-aws-scanner
    command: ["manual"]
    environment:
      DG_API_ENDPOINT: "https://analysis.deployguard.org"
      API_URL: "https://analysis.deployguard.org"
      DG_API_TOKEN: "dg_scanner_cqdIoRombfiO6xSgMdiP2ghK2jgo2uME"
      DG_CLUSTER_ID: "36b72d40-4443-405a-b564-14244b7dbeca"
      DG_SCANNER_TYPE: "aws"
      AWS_REGION: "ap-northeast-2"
      DG_ROLE_ARN: "arn:aws:iam::244105859679:role/deployguard-scanner-role"
      DG_SAVE_LOCAL_COPY: "false"
