{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployguard-aws-scanner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deployguard-aws-scanner.labels" . | nindent 4 }}
  {{- with merge .Values.serviceAccount.annotations (
      .Values.aws.irsa.enabled | ternary
        (dict "eks.amazonaws.com/role-arn" .Values.aws.irsa.roleArn)
        dict
    ) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
