apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "deployguard-scanner.namespace" . }}
  labels:
    {{- include "deployguard-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: scanner