{{- $apiToken := include "deployguard-scanner.apiToken" . -}}
{{- if and (not .Values.api.existingSecret) $apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployguard-scanner.apiTokenSecretName" . }}
  namespace: {{ include "deployguard-scanner.namespace" . }}
  labels:
    {{- include "deployguard-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.existingSecretKey }}: {{ $apiToken | quote }}
{{- end }}
