{{- if and (not .Values.api.existingSecret) .Values.api.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployguard-scanner.apiTokenSecretName" . }}
  namespace: {{ include "deployguard-scanner.namespace" . }}
  labels:
    {{- include "deployguard-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.existingSecretKey }}: {{ .Values.api.token | quote }}
{{- end }}
