# ─────────────────────────────────────────────────────────────────────────────
# secrets.yaml — 민감 정보 (절대 git 커밋 금지!)
# .gitignore에 secrets.yaml 추가 필수
# ─────────────────────────────────────────────────────────────────────────────

deployguard:
  apiToken: "dg_scanner_yljmasnwEJkdZ4K3sA4lz1EzWZXrpbR6"

aws:
  credentials:
    accessKeyId: "youracesskey"
    secretAccessKey: "yoursecretacesskey"
