name: scanner-release-ecr

on:
  push:
    tags:
      - 'agent-v*'
      - 'aws-v*'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set target by tag
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"

          if [[ "$TAG_NAME" == agent-v* ]]; then
            echo "DOCKERFILE=docker/dg-k8s-image.Dockerfile" >> $GITHUB_ENV
            echo "ECR_REPOSITORY=deployguard-agent-scanner" >> $GITHUB_ENV
            echo "IMAGE_TAG=${TAG_NAME#agent-v}" >> $GITHUB_ENV
          elif [[ "$TAG_NAME" == aws-v* ]]; then
            echo "DOCKERFILE=docker/aws-cloud-scanner.Dockerfile" >> $GITHUB_ENV
            echo "ECR_REPOSITORY=deployguard-aws-scanner" >> $GITHUB_ENV
            echo "IMAGE_TAG=${TAG_NAME#aws-v}" >> $GITHUB_ENV
          else
            echo "Unsupported tag: $TAG_NAME"
            exit 1
          fi

      - name: Build image
        run: |
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

          docker build \
            -f $DOCKERFILE \
            -t $IMAGE_URI:$IMAGE_TAG \
            -t $IMAGE_URI:latest \
            .

      - name: Push image
        run: |
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

          docker push $IMAGE_URI:$IMAGE_TAG
          docker push $IMAGE_URI:latest
